# Generated by Django 4.2.9 on 2024-03-28 14:31

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afdeling',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.FloatField(blank=True, null=True)),
                ('afd_name', models.CharField(blank=True, max_length=50, null=True)),
                ('werks', models.FloatField(blank=True, null=True)),
                ('afd_code', models.CharField(blank=True, max_length=50, null=True)),
                ('ha', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('spmon', models.DateField(blank=True, null=True)),
                ('estate', models.CharField(blank=True, max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, dim=4, null=True, srid=32650)),
            ],
            options={
                'db_table': 'Afdeling',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.FloatField(blank=True, null=True)),
                ('afd_name', models.CharField(blank=True, max_length=50, null=True)),
                ('block_name', models.CharField(blank=True, max_length=15, null=True)),
                ('werks', models.FloatField(blank=True, null=True)),
                ('afd_code', models.CharField(blank=True, max_length=50, null=True)),
                ('spmon', models.CharField(blank=True, max_length=50, null=True)),
                ('ha', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('planted', models.CharField(blank=True, max_length=50, null=True)),
                ('block_code', models.CharField(blank=True, max_length=50, null=True)),
                ('yop', models.CharField(blank=True, max_length=50, null=True)),
                ('topo', models.CharField(blank=True, max_length=50, null=True)),
                ('estate', models.CharField(blank=True, max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=32650)),
            ],
            options={
                'db_table': 'Block',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hgu',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.FloatField(blank=True, null=True)),
                ('werks', models.IntegerField(blank=True, null=True)),
                ('comp_code', models.IntegerField(blank=True, null=True)),
                ('spmon', models.DateField(blank=True, null=True)),
                ('ha', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, dim=4, null=True, srid=32650)),
            ],
            options={
                'db_table': 'HGU',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jembatan',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.FloatField(blank=True, null=True)),
                ('werks', models.FloatField(blank=True, null=True)),
                ('afd_name', models.CharField(blank=True, max_length=50, null=True)),
                ('block_name', models.CharField(blank=True, max_length=15, null=True)),
                ('kategory', models.CharField(blank=True, max_length=20, null=True)),
                ('dimensi', models.CharField(blank=True, max_length=20, null=True)),
                ('kondisi', models.CharField(blank=True, max_length=50, null=True)),
                ('topo', models.CharField(blank=True, max_length=50, null=True)),
                ('planted', models.CharField(blank=True, max_length=50, null=True)),
                ('yop', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('x', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('y', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=15, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=32650)),
            ],
            options={
                'db_table': 'Jembatan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Patokhgu',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.FloatField(blank=True, null=True)),
                ('kode', models.CharField(blank=True, max_length=20, null=True)),
                ('x', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('y', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('block_name', models.CharField(blank=True, max_length=10, null=True)),
                ('afd_name', models.CharField(blank=True, max_length=20, null=True)),
                ('no_patok', models.CharField(blank=True, max_length=10, null=True)),
                ('longitude', models.CharField(blank=True, max_length=30, null=True)),
                ('latitude', models.CharField(blank=True, max_length=30, null=True)),
                ('periode', models.CharField(blank=True, max_length=2, null=True)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=32650)),
            ],
            options={
                'db_table': 'PatokHGU',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Planted',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.FloatField(blank=True, null=True)),
                ('afd_name', models.CharField(blank=True, max_length=50, null=True)),
                ('block_name', models.CharField(blank=True, max_length=15, null=True)),
                ('block_sap', models.CharField(blank=True, max_length=3, null=True)),
                ('spmon', models.DateField(blank=True, null=True)),
                ('ha', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('tahun', models.CharField(blank=True, max_length=10, null=True)),
                ('level_1', models.CharField(blank=True, max_length=25, null=True)),
                ('level_2', models.CharField(blank=True, max_length=25, null=True)),
                ('werks', models.CharField(blank=True, max_length=50, null=True)),
                ('ln_cat', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, dim=4, null=True, srid=32650)),
            ],
            options={
                'db_table': 'Planted',
                'managed': False,
            },
        ),
    ]
