# Generated by Django 4.2.9 on 2024-04-12 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0002_afdeling_block_hgu_jembatan_patokhgu_planted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blok',
        ),
    ]
