# Generated by Django 4.2.9 on 2024-04-25 06:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0003_delete_blok'),
    ]

    operations = [
        migrations.CreateModel(
            name='AplikasiTankos',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('afdeling', models.CharField(blank=True, max_length=5, null=True)),
                ('block', models.CharField(blank=True, max_length=5, null=True)),
                ('jml_pokok', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('ha_area', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('tonase', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('aplikasi', models.DateField(blank=True, null=True)),
                ('ton_lap', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('prog_pokok', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('prog_ha', models.IntegerField(blank=True, null=True)),
                ('sph', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=32650)),
            ],
            options={
                'db_table': 'aplikasi_tankos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DumpTankos',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('afdeling', models.CharField(blank=True, max_length=5, null=True)),
                ('block', models.CharField(blank=True, max_length=5, null=True)),
                ('location', models.CharField(blank=True, max_length=10, null=True)),
                ('dumps', models.DateField(blank=True, null=True)),
                ('aplikasi', models.DateField(blank=True, null=True)),
                ('selisih', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('ton_dumps', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('ton_lap', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=32650)),
            ],
            options={
                'db_table': 'dump_tankos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonitoringPatokhgu',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.FloatField(blank=True, null=True)),
                ('kode', models.CharField(blank=True, max_length=20, null=True)),
                ('x', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('y', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('block_name', models.CharField(blank=True, max_length=10, null=True)),
                ('afd_name', models.CharField(blank=True, max_length=20, null=True)),
                ('no_patok', models.CharField(blank=True, max_length=10, null=True)),
                ('longitude', models.CharField(blank=True, max_length=30, null=True)),
                ('latitude', models.CharField(blank=True, max_length=30, null=True)),
                ('periode', models.CharField(blank=True, max_length=2, null=True)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=32650)),
            ],
            options={
                'db_table': 'monitoring_patokhgu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.FloatField(blank=True, null=True)),
                ('afd_name', models.CharField(blank=True, max_length=50, null=True)),
                ('block_name', models.CharField(blank=True, max_length=15, null=True)),
                ('road_cat', models.CharField(blank=True, max_length=30, null=True)),
                ('road_name', models.CharField(blank=True, max_length=20, null=True)),
                ('perkerasan', models.CharField(blank=True, max_length=50, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=50, null=True)),
                ('spmon', models.CharField(blank=True, max_length=50, null=True)),
                ('rd_sym', models.CharField(blank=True, max_length=50, null=True)),
                ('road_code', models.CharField(blank=True, max_length=50, null=True)),
                ('werks', models.FloatField(blank=True, null=True)),
                ('kj', models.CharField(blank=True, max_length=15, null=True)),
                ('panjang', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, dim=4, null=True, srid=32650)),
            ],
            options={
                'db_table': 'road',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Building',
        ),
        migrations.DeleteModel(
            name='Patokhgu',
        ),
        migrations.AlterModelTable(
            name='afdeling',
            table='afdeling',
        ),
        migrations.AlterModelTable(
            name='block',
            table='block',
        ),
        migrations.AlterModelTable(
            name='hgu',
            table='hgu',
        ),
        migrations.AlterModelTable(
            name='jembatan',
            table='jembatan',
        ),
        migrations.AlterModelTable(
            name='planted',
            table='planted',
        ),
    ]
