# Generated by Django 4.2.9 on 2024-05-08 13:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0004_aplikasitankos_dumptankos_monitoringpatokhgu_road_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HguAfdeling',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.FloatField(blank=True, null=True)),
                ('afd_name', models.CharField(blank=True, max_length=50, null=True)),
                ('werks', models.FloatField(blank=True, null=True)),
                ('afd_code', models.CharField(blank=True, max_length=50, null=True)),
                ('ha', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('spmon', models.DateField(blank=True, null=True)),
                ('estate', models.CharField(blank=True, max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, dim=4, null=True, srid=32650)),
            ],
            options={
                'db_table': 'hgu_afdeling',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HguJalan',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.FloatField(blank=True, null=True)),
                ('afd_name', models.CharField(blank=True, max_length=50, null=True)),
                ('block_name', models.CharField(blank=True, max_length=15, null=True)),
                ('road_cat', models.CharField(blank=True, max_length=30, null=True)),
                ('road_name', models.CharField(blank=True, max_length=20, null=True)),
                ('perkerasan', models.CharField(blank=True, max_length=50, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=50, null=True)),
                ('spmon', models.CharField(blank=True, max_length=50, null=True)),
                ('rd_sym', models.CharField(blank=True, max_length=50, null=True)),
                ('road_code', models.CharField(blank=True, max_length=50, null=True)),
                ('werks', models.FloatField(blank=True, null=True)),
                ('kj', models.CharField(blank=True, max_length=15, null=True)),
                ('panjang', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, dim=4, null=True, srid=32650)),
            ],
            options={
                'db_table': 'hgu_jalan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HguJembatan',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.FloatField(blank=True, null=True)),
                ('werks', models.FloatField(blank=True, null=True)),
                ('afd_name', models.CharField(blank=True, max_length=50, null=True)),
                ('block_name', models.CharField(blank=True, max_length=15, null=True)),
                ('kategory', models.CharField(blank=True, max_length=20, null=True)),
                ('dimensi', models.CharField(blank=True, max_length=20, null=True)),
                ('kondisi', models.CharField(blank=True, max_length=50, null=True)),
                ('topo', models.CharField(blank=True, max_length=50, null=True)),
                ('planted', models.CharField(blank=True, max_length=50, null=True)),
                ('yop', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('x', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('y', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=15, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=32650)),
            ],
            options={
                'db_table': 'hgu_jembatan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HguPatok',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.FloatField(blank=True, null=True)),
                ('kode', models.CharField(blank=True, max_length=20, null=True)),
                ('x', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('y', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('block_name', models.CharField(blank=True, max_length=10, null=True)),
                ('afd_name', models.CharField(blank=True, max_length=20, null=True)),
                ('no_patok', models.CharField(blank=True, max_length=10, null=True)),
                ('longitude', models.CharField(blank=True, max_length=30, null=True)),
                ('latitude', models.CharField(blank=True, max_length=30, null=True)),
                ('periode', models.CharField(blank=True, max_length=2, null=True)),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=32650)),
                ('update_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hgu_patok',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HguPlanted',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.FloatField(blank=True, null=True)),
                ('afd_name', models.CharField(blank=True, max_length=50, null=True)),
                ('block_name', models.CharField(blank=True, max_length=15, null=True)),
                ('block_sap', models.CharField(blank=True, max_length=3, null=True)),
                ('spmon', models.DateField(blank=True, null=True)),
                ('ha', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('tahun', models.CharField(blank=True, max_length=10, null=True)),
                ('level_1', models.CharField(blank=True, max_length=25, null=True)),
                ('level_2', models.CharField(blank=True, max_length=25, null=True)),
                ('werks', models.CharField(blank=True, max_length=50, null=True)),
                ('ln_cat', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, dim=4, null=True, srid=32650)),
            ],
            options={
                'db_table': 'hgu_planted',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KaveldOa',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('afd_name', models.CharField(blank=True, max_length=50, null=True)),
                ('block_name', models.CharField(blank=True, max_length=15, null=True)),
                ('shape_leng', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('werks', models.FloatField(blank=True, null=True)),
                ('afd_code', models.CharField(blank=True, max_length=50, null=True)),
                ('spmon', models.CharField(blank=True, max_length=50, null=True)),
                ('ha', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('planted', models.CharField(blank=True, max_length=50, null=True)),
                ('luas20', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('luas20q2', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('block_code', models.CharField(blank=True, max_length=50, null=True)),
                ('yop', models.CharField(blank=True, max_length=50, null=True)),
                ('topo', models.CharField(blank=True, max_length=50, null=True)),
                ('estate', models.CharField(blank=True, max_length=50, null=True)),
                ('driven', models.CharField(blank=True, max_length=20, null=True)),
                ('shape_le_1', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('shape_area', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('kaveld', models.CharField(blank=True, max_length=10, null=True)),
                ('ancak', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, dim=4, null=True, srid=32650)),
            ],
            options={
                'db_table': 'kaveld_oa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TankosAplgeom',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('afdeling', models.CharField(max_length=5)),
                ('block', models.CharField(max_length=5)),
                ('tot_pokok', models.IntegerField(blank=True, null=True)),
                ('ha', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('tot_tonase', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('aplikasi', models.DateField(blank=True, null=True)),
                ('prog_pokok', models.IntegerField(blank=True, null=True)),
                ('prog_tonase', models.FloatField(blank=True, null=True)),
                ('sph', models.FloatField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=32650)),
            ],
            options={
                'db_table': 'tankos_aplgeom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TankosDumpdata',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('afdeling', models.CharField(blank=True, max_length=5, null=True)),
                ('block', models.CharField(blank=True, max_length=5, null=True)),
                ('location', models.CharField(blank=True, max_length=10, null=True)),
                ('dump_date', models.DateField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=32650)),
            ],
            options={
                'db_table': 'tankos_dumpdata',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Afdeling',
        ),
        migrations.DeleteModel(
            name='AplikasiTankos',
        ),
        migrations.DeleteModel(
            name='Block',
        ),
        migrations.DeleteModel(
            name='DumpTankos',
        ),
        migrations.DeleteModel(
            name='Jembatan',
        ),
        migrations.DeleteModel(
            name='MonitoringPatokhgu',
        ),
        migrations.DeleteModel(
            name='Planted',
        ),
        migrations.DeleteModel(
            name='Road',
        ),
    ]
