# Generated by Django 4.2.9 on 2024-05-24 08:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Map', '0006_hgublock'),
    ]

    operations = [
        migrations.CreateModel(
            name='HgublockView',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('afd_name', models.CharField(blank=True, max_length=50, null=True)),
                ('block_name', models.CharField(blank=True, max_length=15, null=True)),
                ('ha', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('st_transform', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=32650)),
            ],
            options={
                'db_table': 'hgublock_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HguplantedView',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('afd_name', models.CharField(blank=True, max_length=50, null=True)),
                ('block_name', models.CharField(blank=True, max_length=15, null=True)),
                ('ha', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('st_transform', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=32650)),
            ],
            options={
                'db_table': 'hguplanted_view',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TankosAplApi',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('block', models.CharField(blank=True, max_length=5, null=True)),
                ('afdeling', models.CharField(blank=True, max_length=5, null=True)),
                ('tot_pokok', models.IntegerField(blank=True, null=True)),
                ('tot_tonase', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('sph', models.FloatField(blank=True, null=True)),
                ('prog_tonase', models.FloatField(blank=True, null=True)),
                ('prog_pokok', models.BigIntegerField(blank=True, null=True)),
                ('prog_ha', models.FloatField(blank=True, null=True)),
                ('last_date', models.DateField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'tankos_apl_api',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TankosDumpApi',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('afdeling', models.CharField(blank=True, max_length=5, null=True)),
                ('block', models.CharField(blank=True, max_length=5, null=True)),
                ('location', models.CharField(blank=True, max_length=10, null=True)),
                ('dump_date', models.DateField(blank=True, null=True)),
                ('apl_date', models.DateField(blank=True, null=True)),
                ('date_diff', models.IntegerField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'tankos_dump_api',
                'managed': False,
            },
        ),
    ]
