# Generated by Django 4.2.9 on 2024-05-08 13:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('objectid', models.FloatField(blank=True, null=True)),
                ('afd_name', models.CharField(blank=True, max_length=50, null=True)),
                ('block_name', models.CharField(blank=True, max_length=15, null=True)),
                ('werks', models.FloatField(blank=True, null=True)),
                ('afd_code', models.CharField(blank=True, max_length=50, null=True)),
                ('spmon', models.CharField(blank=True, max_length=50, null=True)),
                ('ha', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('planted', models.CharField(blank=True, max_length=50, null=True)),
                ('block_code', models.CharField(blank=True, max_length=50, null=True)),
                ('yop', models.CharField(blank=True, max_length=50, null=True)),
                ('topo', models.CharField(blank=True, max_length=50, null=True)),
                ('estate', models.CharField(blank=True, max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, dim=4, null=True, srid=32650)),
            ],
            options={
                'db_table': 'block',
                'managed': False,
            },
        ),
    ]
