# Generated by Django 4.2.9 on 2024-05-24 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MobileAPI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Block',
        ),
    ]
