# Generated by Django 4.2.9 on 2024-03-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jangkos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('object_id', models.FloatField()),
                ('afd_name', models.CharField(max_length=50)),
                ('block_name', models.CharField(max_length=15)),
                ('dumps', models.DateField(blank=True, null=True)),
                ('aplikasi', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('selisih', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Jangkos',
                'managed': False,
            },
        ),
    ]
