# Generated by Django 4.2.9 on 2024-05-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0002_tankosaplpokok_tankosaplsummary_tankosapltonase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TankosDumpview',
            fields=[
                ('gid', models.IntegerField(primary_key=True, serialize=False)),
                ('afdeling', models.CharField(blank=True, max_length=5, null=True)),
                ('block', models.CharField(blank=True, max_length=5, null=True)),
                ('location', models.CharField(blank=True, max_length=10, null=True)),
                ('dump_date', models.DateField(blank=True, null=True)),
                ('apl_date', models.DateField(blank=True, null=True)),
                ('date_diff', models.IntegerField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tankos_dumpview',
                'managed': False,
            },
        ),
    ]
